import './globals.css';

export const metadata = {  
  title: "My Project",
          description: "Generated by Squadbox",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
