import './globals.css';

export const metadata = {  
  title: "Test Portfolio Project",
  description: "Generated by Squabdox",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
